### ISSUE TITLE
Issue Tambahan

### ISSUE THREAD

**Issue by yubliwarokkaid** [erwindosianipar/api-alkitab#19]
Mohon di tambahkan lagi Judul dan Seluruh Passage List mulai dari Judul sampai konten keseluruhan Kejadian Sampai Wahyu. Terima kasih dan sukses selalu

**Comment by erwindosianipar** [comment]
Hi @codeseribu terima kasih atas masukan yang kamu berikan. Saya telah menambahkan _open issues_ untuk menambahkan fitur tersebut, Anda dapat melihatnya di tiket _issues_ #20

Atau Anda juga dapat melihat _progress_ pengerjaannya pada [_tracking card_](https://github.com/users/erwindosianipar/projects/2#card-58446612) berikut ini

Terima kasih
