### ISSUE TITLE
Nested JSON

### ISSUE THREAD

**Issue by raselldev** [erwindosianipar/api-alkitab#21]
Selamat malam, saya ingin menggunakan API ini, akan tetapi menurut saya penggunaannya sulit di ReactJS dikarenakan JSON yang dihasilkan Nested JSON

**Comment by erwindosianipar** [comment]
Hallo @raselldev nested JSON disini digunakan untuk menampilkan list ayat, Anda dapat menggunakan perulangan untuk menampilkan informasi yang dibutuhkan dengan parse list JSON tersebut.

Untuk implementasinya Anda dapat melihat repository https://github.com/erwindosianipar/read-alkitab dengan menggunakan VueJS yang tidak terlalu berbeda implementasinya dengan ReactJS.

Terima kasih

**Comment by erwindosianipar** [comment]
Hallo @raselldev saya telah mencoba mengimplementasikan penggunaan API ini untuk ReactJS, Anda dapat mencoba menerapkan hal yang sama dan semoga ini membantu.

https://codesandbox.io/s/winter-monad-ql7vm

Terima kasih
