### ISSUE TITLE
error akses api

### ISSUE THREAD

**Issue by Fharhanamrin** [erwindosianipar/api-alkitab#26]
halo team, apakah apinya tidak bisa di akses sekarang ?

**Comment by Fharhanamrin** [comment]
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by erwindosianipar** [comment]
I apologize for this, it's based on the condition that Heroku where I host this API is no longer able to run for free

https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

I will try to re-run this bible API so that it can be used as it was

**Comment by erwindosianipar** [comment]
Please watch this issue I mentioned on https://github.com/erwindosianipar/api-alkitab/issues/27
